//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aurea.Maintenance.Debugger.AEPEnergy.MockData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MockDataXMLs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockDataXMLs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aurea.Maintenance.Debugger.AEPEnergy.MockData.MockDataXMLs", typeof(MockDataXMLs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;206546&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4106784&quot; CustName=&quot;Gerald Smith&quot; LastName=&quot;Smith&quot; FirstName=&quot;Gerald&quot; AcctsRecID=&quot;106542&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;106816&quot; MailAddrId=&quot;213171&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefitsPlan= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_01 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;163072&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4153235&quot; CustName=&quot;ISABEL RAMON MENDOZA&quot; LastName=&quot;RAMON MENDOZA&quot; FirstName=&quot;ISABEL&quot; AcctsRecID=&quot;153071&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;309101&quot; BillCycle=&quot;309101&quot; RateID=&quot;153684&quot; MailAddrId=&quot;306395&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; Life [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_02 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;116878&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4107119&quot; CustName=&quot;Bruce A Sprague&quot; LastName=&quot;Sprague&quot; FirstName=&quot;Bruce A&quot; AcctsRecID=&quot;106877&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;107154&quot; MailAddrId=&quot;213845&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_03 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;123581&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4113789&quot; CustName=&quot;James Coyne&quot; LastName=&quot;Coyne&quot; FirstName=&quot;James&quot; AcctsRecID=&quot;113580&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;113980&quot; MailAddrId=&quot;227314&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefitsPlan=&quot;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_04 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;197124&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4184306&quot; CustName=&quot;Walter Kustala&quot; LastName=&quot;Kustala&quot; FirstName=&quot;Walter&quot; AcctsRecID=&quot;187123&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;188113&quot; MailAddrId=&quot;370783&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefitsP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_05_Current {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_05_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;116878&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4107119&quot; CustName=&quot;Bruce A Sprague&quot; LastName=&quot;Sprague&quot; FirstName=&quot;Bruce A&quot; AcctsRecID=&quot;106877&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;107154&quot; MailAddrId=&quot;213845&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_06 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;123581&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4113789&quot; CustName=&quot;James Coyne&quot; LastName=&quot;Coyne&quot; FirstName=&quot;James&quot; AcctsRecID=&quot;113580&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;113980&quot; MailAddrId=&quot;227314&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefitsPlan=&quot;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_07 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;116543&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4106784&quot; CustName=&quot;Gerald Smith&quot; LastName=&quot;Smith&quot; FirstName=&quot;Gerald&quot; AcctsRecID=&quot;106542&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;106816&quot; MailAddrId=&quot;213171&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefitsPlan= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_08 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;163072&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4153235&quot; CustName=&quot;ISABEL RAMON MENDOZA&quot; LastName=&quot;RAMON MENDOZA&quot; FirstName=&quot;ISABEL&quot; AcctsRecID=&quot;153071&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;309101&quot; BillCycle=&quot;309101&quot; RateID=&quot;153684&quot; MailAddrId=&quot;306395&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; Life [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_09 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;127678&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4117837&quot; CustName=&quot;Jennifer Bent&quot; LastName=&quot;Bent&quot; FirstName=&quot;Jennifer&quot; AcctsRecID=&quot;117677&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;306201&quot; BillCycle=&quot;306201&quot; RateID=&quot;118161&quot; MailAddrId=&quot;235539&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefitsPla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_10 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;19981&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4010979&quot; CustName=&quot;Robert E Martin Jr&quot; LastName=&quot;Martin Jr&quot; FirstName=&quot;Robert E&quot; AcctsRecID=&quot;9980&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;309101&quot; BillCycle=&quot;309101&quot; RateID=&quot;10018&quot; MailAddrId=&quot;19973&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; LifeSupportIn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_11 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;116549&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4106790&quot; CustName=&quot;Thomas Vonortas&quot; LastName=&quot;Vonortas&quot; FirstName=&quot;Thomas&quot; AcctsRecID=&quot;106548&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;106822&quot; MailAddrId=&quot;213183&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBenefit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_12 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;117002&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;1&quot; CustNo=&quot;4107243&quot; CustName=&quot;Thomas L Crawford&quot; LastName=&quot;Crawford&quot; FirstName=&quot;Thomas L&quot; AcctsRecID=&quot;107001&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;305901&quot; BillCycle=&quot;305901&quot; RateID=&quot;107278&quot; MailAddrId=&quot;214099&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;R&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAccts=&quot;1&quot; ConsolidatedInv=&quot;Y&quot; SummaryInv=&quot;N&quot; TDSPTemplateID=&quot;1&quot; TDSPGroupID=&quot;1&quot; SpecialBen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_13_Next {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_13_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;Customer CustID=&quot;178066&quot; CSPID=&quot;1&quot; CustomerTypeID=&quot;2&quot; CustNo=&quot;4168219&quot; CustName=&quot;American Vintage Warehouse Hilliard&quot; LastName=&quot;Hilliard&quot; FirstName=&quot;American Vintage Warehouse&quot; CompanyName=&quot;American Vintage Warehouse Hilliard&quot; AcctsRecID=&quot;168065&quot; DistributedAR=&quot;N&quot; ProductionCycle=&quot;309101&quot; BillCycle=&quot;309101&quot; RateID=&quot;168723&quot; MailAddrId=&quot;333475&quot; MailToSiteAddress=&quot;0&quot; MasterCustID=&quot;10001&quot; Master=&quot;N&quot; CustStatus=&quot;A&quot; CustType=&quot;C&quot; Taxable=&quot;Y&quot; LateFees=&quot;N&quot; NoOfAcct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_BasicTC_14_Next2 {
            get {
                return ResourceManager.GetString("AESCIS_16615_BasicTC_14_Next2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- don&apos;t forget to reflag by changing ProcessFlag to 0--&gt;
        ///  &lt;daes_AEPEnergyMarket..tbl_814_header _x0038_14_Key=&quot;2445714&quot; MarketFileId=&quot;44861&quot; TransactionSetId=&quot;814&quot; TransactionSetControlNbr=&quot;&quot; TransactionSetPurposeCode=&quot;S&quot; TransactionNbr=&quot;F150003978462520171227-S&quot; TransactionDate=&quot;&quot; ReferenceNbr=&quot;F150003978462520171227&quot; ActionCode=&quot;C&quot; TdspDuns=&quot;DOMINIONG&quot; TdspName=&quot;Dominion East Ohio&quot; CrDuns=&quot;077778954&quot; CrName=&quot;AEPEnergy&quot; ProcessFlag=&quot;0&quot; ProcessDate=&quot;20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_TC_05_814Accept {
            get {
                return ResourceManager.GetString("AESCIS_16615_TC_05_814Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;CustomerTransactionRequest RequestID=&quot;4727194&quot; CustID=&quot;19981&quot; PremID=&quot;9994&quot; TransactionType=&quot;814&quot; ActionCode=&quot;C&quot; TransactionDate=&quot;2017-12-06T00:00:00&quot; Direction=&quot;1&quot; RequestDate=&quot;2017-12-06T00:00:00&quot; ServiceActionCode=&quot;A&quot; ServiceAction=&quot;S&quot; StatusCode=&quot;AMTRJ&quot; SourceID=&quot;2420521&quot; TransactionNumber=&quot;ACPC12383860001020171206-S&quot; ReferenceNumber=&quot;ACPC12383860001020171206&quot; ESIID=&quot;123838600010&quot; ProcessFlag=&quot;0&quot; EventCleared=&quot;1&quot; EventValidated=&quot;0&quot; DelayedEventValidate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_TC_11_814Accept {
            get {
                return ResourceManager.GetString("AESCIS_16615_TC_11_814Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;!--Scenario Test EventGenerator(ChangeRequestEvaluation) and EventHandler(ChangeRequest) EventTypeID = 16--&gt;
        ///  &lt;RateTransition RateTransitionID=&quot;974480&quot; CustID=&quot;19981&quot; RateID=&quot;192534&quot; UserID=&quot;289&quot; CreatedDate=&quot;2017-12-06T09:31:40.710&quot; SwitchDate=&quot;2017-12-06T00:00:00&quot; EndDate=&quot;2017-12-05T00:00:00&quot; StatusID=&quot;2&quot; SoldDate=&quot;2017-12-05T23:31:41&quot; RolloverFlag=&quot;0&quot; /&gt;
        ///  &lt;!--ChangeRequest ChangeRequestID=&quot;75117&quot; CustomerID=&quot;19981&quot; ElementID=&quot;6&quot; ElementPrimaryKey=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_TC_11_RateTransitionOK {
            get {
                return ResourceManager.GetString("AESCIS_16615_TC_11_RateTransitionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- don&apos;t forget to reflag by changing ProcessFlag to 0--&gt;
        ///  &lt;daes_AEPEnergyMarket..tbl_814_header _x0038_14_Key=&quot;2512355&quot; MarketFileId=&quot;45742&quot; TransactionSetId=&quot;814&quot; TransactionSetControlNbr=&quot;&quot; TransactionSetPurposeCode=&quot;S&quot; TransactionNbr=&quot;F444030384572120180105-S&quot; TransactionDate=&quot;&quot; ReferenceNbr=&quot;F444030384572120180105&quot; ActionCode=&quot;C&quot; TdspDuns=&quot;DOMINIONG&quot; TdspName=&quot;Dominion East Ohio&quot; CrDuns=&quot;077778954&quot; CrName=&quot;AEPEnergy&quot; ProcessFlag=&quot;0&quot; ProcessDate=&quot;20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_TC_13_814Accept {
            get {
                return ResourceManager.GetString("AESCIS_16615_TC_13_814Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- don&apos;t forget to reflag by changing ProcessFlag to 0--&gt;
        ///  &lt;daes_AEPEnergyMarket..tbl_814_header _x0038_14_Key=&quot;2513245&quot; MarketFileId=&quot;45832&quot; TransactionSetId=&quot;814&quot; TransactionSetControlNbr=&quot;&quot; TransactionSetPurposeCode=&quot;S&quot; TransactionNbr=&quot;ACPC19342666001720180105-S&quot; TransactionDate=&quot;20180105&quot; ReferenceNbr=&quot;ACPC19342666001720180105&quot; ActionCode=&quot;C&quot; TdspDuns=&quot;COLUMBIAG&quot; TdspName=&quot;Columbia Gas&quot; CrDuns=&quot;077778954&quot; CrName=&quot;AEP Energy&quot; ProcessFlag=&quot;0&quot; ProcessD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AESCIS_16615_TC_14_814Accept {
            get {
                return ResourceManager.GetString("AESCIS_16615_TC_14_814Accept", resourceCulture);
            }
        }
    }
}
